### ISSUE TITLE
Job Action: Switch

### ISSUE THREAD

**Issue by despadam** [SciCatProject/backend#1658]
From https://github.com/SciCatProject/scicat-backend-next/issues/1124

Filters (eg different actions depending on the status, storing to different location)

For OpenEM project: Filters to be implemented later, when ETH is also onboarded.

**Comment by sbliven** [comment]
I've been thinking about the config option syntax for this.  Does this look reasonable? Any options on the spellings (eg `switch` vs `filter`)?

```yaml
- actionType: switch
  # Either 'request' or 'datasets', analogous to validateaction
  scope: datasets
  # JSONPath to extract the value from the given scope
  property: datasetlifecycle.storageLocation
  # Cases are tested sequentially, with the first match applied (no fallthrough)
  cases:
      # match applies a regex. Assumes the property is a string
    - match: /PSI.*/i
      actions:
      - actionType: log
        performJob: "Sending job to PSI"
      # schema applies an AJV schema
    - schema:
        const: ETHZ
      actions:
      - actionType: log
        performJob: "Sending job to ETHZ"
      # default case (no match or schema)
    - actions:
      - actionType: error
        code: 400
        message: Invalid storageLocation
```
