### ISSUE TITLE
Enable default validate job actions

### ISSUE THREAD

**Issue by sbliven** [SciCatProject/backend#1692]
## Summary

With #1473 operators are required to add validate dataset properties themselves to reproduce the previous validation behavior. Specifically, the following actions were previously included by default:

```
jobs:
  - jobType: archive
    create:
      actions:
        - actionType: validate
          datasets:
            "datasetlifecycle.archivable":
              const: true
  - jobType: retrieve
    create:
      actions:
      - actionType: validate
        datasets:
          "datasetlifecycle.retrievable":
            const: true
  - jobType: public
    create:
      actions:
        - actionType: validate
          datasets:
            isPublished:
              const: true
```

Since these were previously hard-coded for the `archive`, `retrieve` and `public` datatypes, it is potentially dangerous to now expect operators to include them in the job config file.

## Proposed change

Add a new property to JobConfig, `defaultActions?: "archive" | "retrieve" | "public" | bool` with the following behavior
- The string `"archive"` cause the default validate action from above to get prepended to the action list for the job, validating `datasetlifecycle.archivable`. Retrieve and public are analogous.
- `true` or `undefined` check if the jobType matches one of the three defined jobs and adds the default action if appropriate. This means the default behavior will match the v3 validation
- `false` disables adding the default (in case operators want to define validation explicitely)

### Examples

```
jobs:
  - jobType: archive
    # default datasetlifecycle.archivable validation
    create:
      auth: ...
  - jobType: custom_archive
    # same validation as above but with a custom job name
    defaultActions: archive
  - jobType: public
    # allow publishing datasets even if they aren't marked as published (bad idea!)
    defaultActions: false
    create:
      auth:...
```
