### ISSUE TITLE
Mismatch Between API Response and Schema for isValid Endpoints

### ISSUE THREAD

**Issue by patrickmadela** [SciCatProject/backend#1756]
## Summary
The response from the `isValid` endpoints does not match the API schema definition.

## Steps to Reproduce
1. Call the `isValid` endpoint.
2. Observe the response format.
3. Compare it with the schema definition in the API documentation.

## Current Behaviour

The API returns a response in the following format:
```json
{
  "valid": false
}
```

But the schema is defined as:
```yaml
IsValidResponse:
  type: object
  properties:
    isvalid:
      type: boolean
  required:
    - isvalid
```

Additionally, the `/api/v3/proposals/isValid` endpoint returns a JSON object of type `IsValidResponse`, while the schema defines it as returning a boolean.

## Expected Behaviour

The schema definition should match the API response:
```yaml
IsValidResponse:
  type: object
  properties:
    valid:
      type: boolean
  required:
    - valid
```

For the `/api/v3/proposals/isValid` endpoint, the expected response format is:
```yaml
/api/v3/proposals/isValid:
...
  responses:
    '200':
      description: >-
        Check if the provided proposal passes validation. It returns true if
        the validation is passed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IsValidResponse'
```

## Details
- The schema should be updated to ensure consistency with the API response.
- This issue affects endpoints that rely on `IsValidResponse`.
- Related components or tests should be checked for similar discrepancies.

Please confirm and let me know if further details are needed. Thank you!
