### ISSUE TITLE
allow multiple auth values in jobConfig.yaml

### ISSUE THREAD

**Issue by sbliven** [SciCatProject/backend#1912]
## Summary

`JobOperation.auth` currently takes a single `user`, `@group`, or `#jobAuth` value. Sometimes it would be nice to allow several groups access. I propose allowing an array here as well.

Example jobConfig.yaml:
```yaml
jobs:
  - jobType: custom
    create:
      auth:
        - @managers
        - @specialusers
    update:
      auth: "archivemanager"
```
