### ISSUE TITLE
Startup delay of Docker container

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/backend#764]
# Startup delay of Docker container

When spinning up a Docker container with the image provided on GH, it takes a while for the server to become available. But it seems hard to predict how long that will take.

## The problem

In Scitacean, some tests run against a backend deployed via the Docker container. After staring the container, the tests attempt to connect repeatedly for some amount of time until either the connection succeeds or a max time is reached. In the latter case, the tests fail. (See https://github.com/SciCatProject/scitacean/blob/94fb44e8d84dff6e1e0feb76c52dccee19984dcb/src/scitacean/testing/backend/_backend.py#L78-L123)
Currently, it is configured to wait up to 20s before timing out. But it frequently does time out, both on my local machine and on GH actions. This happens so frequently, that rarely all tests in the test matrix on GH pass.
I even tried to increase the wait time to 2min without any success.

Is there something that needs to be done to ensure that SciCat starts properly?

And is there a way to reliably wait for it to come online? E.g., it would be good if `docker compose up` would wait until the server is available.

## Context

I use the docker-compose file below with
```
docker compose --file <filename> up --detach --force-recreate
```
```yaml
services:
  mongodb:
    image: bitnami/mongodb:4.2
    volumes:
      - mongodb_data:/bitnami
    ports:
      - "27017:27017"

  scicat:
    image: ghcr.io/scicatproject/backend-next:stable
    container_name: scitacean-test-scicat
    depends_on:
      - mongodb
    ports:
      - 3000:PLACEHOLDER
    environment:
      DOI_PREFIX: DOI.SAMPLE.PREFIX
      HTTP_MAX_REDIRECTS: 1  # Scitacean should not require redirects
      HTTP_TIMEOUT: 5000  # in ms
      JWT_EXPIRES_IN: 3600  # in s (expiry of token)
      JWT_SECRET: a_scicat_secret
      LOGBOOK_ENABLED: no  # we don't test these endpoints
      MONGODB_URI: mongodb://mongodb:27017/scicat

      # Those are configured in Python
      PID_PREFIX: PLACEHOLDER
      SITE: PLACEHOLDER
      PORT: PLACEHOLDER

volumes:
  mongodb_data:
    driver: local
```
